@baseUrl = http://localhost:3001/api
@personId = 6a79876ce0f70b18f6af01a8


### retrieve all the persons
GET {{baseUrl}}/persons

### retireve a sepcifc person 
GET {{baseUrl}}/persons/{{personId}}

### Add a person
POST {{baseUrl}}/persons
Content-Type: application/json

{
    "name":"Kevin Kiptum",
    "number":"038391333"
}

### Deletes a person
DELETE {{baseUrl}}/persons/{{personId}} 


### Update a person's number
# Replace the ID with a real ID
PUT http://localhost:3001/api/persons/6a79bc6535e34aedcd4944b7
Content-Type: application/json

{
    "name":"Kevin Kiptum",
    "number":"038391333455"
}
