@baseUrl = http://localhost:3001
@notesUrl = {{baseUrl}}/api/notes
@usersUrl = {{baseUrl}}/api/users
@loginUrl = {{baseUrl}}/api/login
@userId= 6a844b8182b42b693c895e08
@noteId = 67cadab408282ee8ed1e61d0

### Create note
POST {{notesUrl}}
Content-Type: application/json
Authorization: Bearer {{your token here}}

{
  "content": "I have managed to push data to mongo db and also the user id",
  "important": false,
  "userId":"{{userId}}"
}

### Get all notes
GET {{notesUrl}}

### Get one note
GET {{notesUrl}}/here

### Update note
PUT {{notesUrl}}/{{noteId}}
Content-Type: application/json

{
  "content": "HTML is easy",
  "important": true
}

### Delete note
DELETE {{notesUrl}}/{{noteId}}

### Create user
POST {{usersUrl}}
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}

### Get all users
GET {{usersUrl}}

###
POST  {{loginUrl}}
Content-Type: application/json

{
  "username": "root",
  "password": "salainen"
}
