@baseUrl=http://localhost:3003/api

############ USERS ########

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salasana"
}

###
GET {{baseUrl}}/users

############ BLOGS ########

###
GET {{baseUrl}}/blogs

###
POST {{baseUrl}}/blogs
Content-Type: application/json

{
  "title": "Learning Backend",
  "author": "McMnyages",
  "url": "https://example.com/fullstack",
  "likes": 30
}

###
DELETE {{baseUrl}}/blogs/6a7f2d8b0519bb42ac4566ee

###
PUT {{baseUrl}}/blogs/6a7f2bbea963968e694211ed
Content-Type: application/json

{
  "title": "Updated blog title",
  "author": "Updated Author",
  "url": "https://example.com/updated",
  "likes": 15
}
